Feature/no02
taishiasami123/php-api-docker pull request #3
Opened 2020-04-16 09:51 UTC by taishiasami123

■完了
・各機能内のSQLをdb.phpに移植した。

■検討事項
・似たようなSQLをまとめ，db.phpを整理できないか。
・トークンやパラメータを受け取る処理も1つのファイル，クラスとして独立させられるのではないか。

2020-04-17 02:53 UTC, Yuzunoha commented on html/Db.php
> +class db
クラス名はパスカルケース(アッパーキャメルケース)にしてください。小文字で始まるクラス名は混乱の元なので。

2020-04-17 02:56 UTC, Yuzunoha commented on html/Db.php
> +      // 削除系
削除系という概念は無く、更新系に含まれます。再設計が必要となります

2020-04-17 02:59 UTC, Yuzunoha commented on html/Db.php
> +      sendResponse($message);
DBクラスがhttpレスポンスを送信する役割を持つのはよろしくないです。
DBクラスはDB操作に集中し、参照系なら取得結果を、更新系なら更新の成否を返却するようにしましょう。

2020-04-17 03:34 UTC, Yuzunoha commented on html/Db.php
> +      sendResponse($message);
追伸

>DBクラスがhttpレスポンスを送信する役割を持つのはよろしくない

本件は正常系なのでこの通りですが、例外処理においてはDBでエラーになりましたというレスポンスを送信してdie()するのはよいと思います。

2020-04-22 04:56 UTC, yusaku-inamura approved these changes
確認しました~LGTMです 🙆‍♂️

2020-04-22 05:10 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-04-22 05:10 UTC, choimake commented on html/Db.php
> +    {
229行目 `insertPostDB`
240行目 `updatePostDb`
「DB」と「Db」の命名規則が異なっています。どちらかの形式に統一するよう修正お願いします。

2020-04-22 05:12 UTC, yusaku-inamura requested changes
ちょっとみる範囲間違えてしまったので見直しますね。
少々お待ちを 🙇

2020-04-22 05:21 UTC, himaru-jp requested changes
コメントしました。

2020-04-22 05:21 UTC, himaru-jp commented on html/Db.php
> +        Db::prepareAndExecute($sql, $params, false);
isUpdate = falseだと、fetchAllが実行されてしまいます。
ユズノハさんの指摘の通り修正をお願いします。投稿削除の箇所も同様です。
prepareAndExecuteメソッドを含めて修正をお願いします。

2020-04-22 07:49 UTC, yusaku-inamura requested changes
すみません!
コメントしたのでこちらも併せて修正願います!

2020-04-22 07:49 UTC, yusaku-inamura commented on html/Db.php
> +            ':id' => [$id, PDO::PARAM_INT],
バインドの型が `selectUserByIdFetchAll()` と違いますね。
intの方が正しそうな気はしますが・・・。

2020-04-22 07:49 UTC, yusaku-inamura commented on html/index.php
> +require_once dirname(__FILE__) . '/db.php';
`html/Db.php` がファイル名ですがこの書き方で大丈夫ですか?
もしローカルで動いているなら、なんとなくですがアップルのファイルシステム(APFS)だから大文字小文字を判別していないだけで、linux系のサーバーにあげたらエラーになりそうな気がしてます。

2020-04-22 08:20 UTC, taishiasami123 commented
`return $stmt->execute();`
としてexecuteの結果を受け取っていますが，結果によるエラーハンドリングはできていません。別ブランチで対応したいと思います。

2020-04-23 03:26 UTC, Yuzunoha commented on html/db.php
> +            'id' => [$insertedUserId, PDO::PARAM_INT],
```suggestion
            ':id' => [$insertedUserId, PDO::PARAM_INT],
```
https://www.php.net/manual/ja/sqlite3stmt.bindvalue.php
名前にコロンを付け忘れるとPHPが勝手に補うのですね。知らなかった。
統一したいので他と同様コロンを付けましょう。

2020-04-23 03:28 UTC, Yuzunoha commented on html/db.php
> +    }
`selectUserBySelectedIdFetchAll`と`selectUserByInsertedUserIdFetchAll`は同じ処理なので一つにするべきです。

`selectUserByUserIdFetchAll`一つでよいかと。

2020-04-23 03:29 UTC, Yuzunoha commented on html/db.php
> +            'id' => [$insertedId, PDO::PARAM_INT],
```suggestion
            ';id' => [$insertedId, PDO::PARAM_INT],
```

2020-04-23 03:30 UTC, Yuzunoha commented on html/db.php
> +            'searchKeyword' => [$searchKeyword, PDO::PARAM_STR],
```suggestion
            ':searchKeyword' => [$searchKeyword, PDO::PARAM_STR],
```

2020-04-23 03:36 UTC, Yuzunoha commented on html/index.php
> +require_once dirname(__FILE__) . '/db.php';
クラス名が`Db`なので
ファイル名も`Db.php`
require_once文は`require_once dirname(__FILE__) . '/Db.php';`
にすべきですね。

2020-04-23 03:45 UTC, taishiasami123 commented on html/db.php
> +    }
bindValueで渡したい変数が$insertedUserIdと$selectedIdの２種類あるため，2つの関数に分けて書きました。処理は同じだが渡したい変数が異なる場合，どのように書くのが適切でしょうか。

2020-04-23 06:27 UTC, Yuzunoha commented on html/db.php
> +    }
今回の場合渡したい変数はどちらも`userId`なので、渡したい変数は同じです。

処理は同じだが意味合いに応じてどうしても関数を分けたいのであれば下記のように書きますが、不必要なのでこれを通すためにはレビュアを説得する必要があります。

```
    public static function selectUserByIdFetchAll(int $insertedUserId)
    {
        $sql = 'SELECT id, name, bio, created_at, updated_at FROM users WHERE id = :id';
        $params = [
            'id' => [$insertedUserId, PDO::PARAM_INT],
        ];
        return Db::executeAndFetchAll($sql, $params);
    }

    // insertされたuserのidに合致するuserを再度取得する
    public static function selectUserByInsertedUserIdFetchAll(int $insertedUserId)
    {
        return Db::selectUserByIdFetchAll($insertedUserId);
    }

    // updateされたuserのidに合致するuserを再度取得する
    public static function selectUserBySelectedIdFetchAll(int $selectedId)
    {
        return Db::selectUserByIdFetchAll($selectedId);
    }
```

2020-04-24 06:07 UTC, Yuzunoha commented on html/Db.php
> +        $sql = 'SELECT id, name, bio, created_at, updated_at FROM users WHERE id = :id';
しいて言えば `selectUserByTokenFromUsersFetchAll` に比べて `selectUserByUserIdFromUsersFetchAll` では取得するカラムを絞っている(tokenとかを落としている)ので、関数名からそれがわかるようにするとよいです。

一例として`selectUserByUserIdFromUsersFetchAllForPublic` 等、レスポンスからpasswordやtoken等の機密情報を落とす関数には共通で `forPublic` を付ける等のアイデアがありますね。

2020-04-24 06:54 UTC, Yuzunoha approved these changes
OKです承認しました！リファクタリング第一弾の水準を満たしていると思います！！
変数名、関数名は長いですが使ったり新たに作ったりする際に悩むことが少なくできそうですね。

2020-04-24 06:56 UTC, merged